version: 2
updates:
  - package-ecosystem: nuget
    directory: "/src"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      prefix-development: chore(dev)
    labels:
      - "enhancement"
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
    labels:
      - "enhancement"
    # Allow up to 5 open pull requests for nuget dependencies
    open-pull-requests-limit: 20